name: A basic flow
on: push
jobs:
  job1:
    name: first job to run
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo "Testing on Ubuntu..."
      - name: Step two
        run: echo "Ubuntu test by Katie" > test-ubuntu.txt
             cat test-ubuntu.txt
             echo "Ubuntu tests completed"
  job2:
    name: Second job to run
    runs-on: windows-latest
    steps:
      - name: Step two of job2
        run: echo "Testing on Windows..."